// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhz8Rq8r7gLnfegcmKA2usSVDUbyrFGdc',
    appId: '1:239812637774:web:14d2578fc00222099c7f1f',
    messagingSenderId: '239812637774',
    projectId: 'point-of-service-c3891',
    authDomain: 'point-of-service-c3891.firebaseapp.com',
    storageBucket: 'point-of-service-c3891.firebasestorage.app',
    measurementId: 'G-79B8XNPJLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAegpT8rw0dFA5h9ox4Jl3H0A4_c7Wbs',
    appId: '1:239812637774:android:ed831bec5daba8de9c7f1f',
    messagingSenderId: '239812637774',
    projectId: 'point-of-service-c3891',
    storageBucket: 'point-of-service-c3891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9C_n8D0hGbAZW7O1hrh_MdAGEMmJCC-k',
    appId: '1:239812637774:ios:2b394e20e67f69009c7f1f',
    messagingSenderId: '239812637774',
    projectId: 'point-of-service-c3891',
    storageBucket: 'point-of-service-c3891.firebasestorage.app',
    iosBundleId: 'com.example.pointOfService',
  );
}
